name: Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://devops-wiki.github.io/JonielOliveira.github.io/
      # url: ${{ secrets.PAGE_URL }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Versão desejada do Python

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Substitua pelo nome do seu arquivo de requisitos

    - name: Run freeze.py
      run: |
        python development/freeze.py  # Substitua pelo caminho e nome do seu arquivo freeze.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./development/build # Diretório gerado pelo freeze.py
